/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hamamspa;


import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author rochdi
 */
public class Départ extends javax.swing.JFrame {

    /**
     * Creates new form Départ
     */
    public Départ() {
        initComponents();
        populateComboBox();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVerifier = new javax.swing.JButton();
        comboidClient = new javax.swing.JComboBox<>();
        lblNumero = new javax.swing.JLabel();
        btnbouhdha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 104, 97));
        jPanel1.setPreferredSize(new java.awt.Dimension(1727, 726));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID Client :");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Numero Chambre :");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnVerifier.setBackground(new java.awt.Color(52, 104, 86));
        btnVerifier.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnVerifier.setForeground(new java.awt.Color(255, 255, 255));
        btnVerifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/check-mark.png"))); // NOI18N
        btnVerifier.setText("Verifier");
        btnVerifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifierActionPerformed(evt);
            }
        });

        comboidClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboidClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboidClientActionPerformed(evt);
            }
        });

        lblNumero.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 51, 51));

        btnbouhdha.setBackground(new java.awt.Color(52, 104, 86));
        btnbouhdha.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnbouhdha.setForeground(new java.awt.Color(255, 255, 255));
        btnbouhdha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/exit.png"))); // NOI18N
        btnbouhdha.setText("Libérer Client");
        btnbouhdha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbouhdhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnbouhdha)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerifier, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(comboidClient, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboidClient, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerifier, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbouhdha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1816, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1869, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2097, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
 
    

    private void populateComboBox() {
    comboidClient.removeAllItems(); 

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/producttbl", "root", "");
        Statement statement = conn.createStatement();
        ResultSet resultSet = statement.executeQuery("SELECT * FROM reservations");
        while (resultSet.next()) {
            String id = resultSet.getString("id");
            comboidClient.addItem(id); 
        }
        statement.close();
        conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    
    private void comboidClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboidClientActionPerformed
    }//GEN-LAST:event_comboidClientActionPerformed

    private void btnbouhdhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbouhdhaActionPerformed
     try {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/producttbl", "root", "");
    Statement statement = conn.createStatement();

    
    ResultSet resultSetRoom = statement.executeQuery("SELECT * FROM room WHERE ava = 'Occupée'");
    if (resultSetRoom.next()) {
        String roomNumber = resultSetRoom.getString("room");
        statement.executeUpdate("UPDATE room SET ava = 'Disponible' WHERE room = '" + roomNumber + "'");
        lblNumero.setText(roomNumber);
    }

    
    ResultSet resultSet = statement.executeQuery("SELECT * FROM reservations");
    while (resultSet.next()) {
        String id = resultSet.getString("id");
        comboidClient.addItem(id); 
    }


    String customerId = (String) comboidClient.getSelectedItem();
    String deleteSql = "DELETE FROM reservations WHERE id = ?";
    PreparedStatement deleteSt = conn.prepareStatement(deleteSql);
    deleteSt.setString(1, customerId); 
    deleteSt.executeUpdate();
    deleteSt.close();

    ImageIcon icon = new ImageIcon("C:\\Users\\rochdi\\Documents\\NetBeansProjects\\HamamSpa\\src\\images\\imgHamam\\check-mark.png");
    JOptionPane.showMessageDialog(this, "Mettra A jour avec Success! , chambre Disponible Maintenant", "Success", JOptionPane.INFORMATION_MESSAGE, icon);
    
    populateComboBox();
    statement.close();
    conn.close();
} catch (SQLException e) {
    e.printStackTrace();
}


    }//GEN-LAST:event_btnbouhdhaActionPerformed

    private void btnVerifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifierActionPerformed
       conn c = new conn();
                try{
                    ResultSet resultSet = c.statement.executeQuery("select * from reservations where id = '"+comboidClient.getSelectedItem()+"'");
                    while (resultSet.next()){
                        lblNumero.setText(resultSet.getString("room"));
                        
                    }
                }catch (Exception E){
                    E.printStackTrace();
                }

    }//GEN-LAST:event_btnVerifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Départ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Départ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Départ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Départ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Départ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerifier;
    private javax.swing.JButton btnbouhdha;
    private javax.swing.JComboBox<String> comboidClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNumero;
    // End of variables declaration//GEN-END:variables
}
