/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hamamspa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rochdi
 */
public class InformationsClient extends javax.swing.JFrame {

    /**
     * Creates new form InformationsClient
     */
    public InformationsClient() {
        initComponents();
        showinformations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableClient = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combogenre = new javax.swing.JComboBox<>();
        comboCateoryID = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnresetfilter = new javax.swing.JButton();
        btnrechercher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 104, 97));
        jPanel1.setPreferredSize(new java.awt.Dimension(1599, 1088));

        tableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Category ID", "Number ID", "Name", "Gender", "Date Anniverssaire", "Adresse", "Email", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableClient.setGridColor(new java.awt.Color(0, 0, 153));
        tableClient.setIntercellSpacing(new java.awt.Dimension(0, 1));
        tableClient.setRowHeight(40);
        tableClient.setSelectionBackground(new java.awt.Color(11, 114, 129));
        tableClient.setShowGrid(true);
        tableClient.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tableClientAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableClient);

        jPanel3.setBackground(new java.awt.Color(11, 114, 129));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Genre :");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        combogenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme", "" }));

        comboCateoryID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passport", "Carte Identité", "Driving Licence" }));
        comboCateoryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCateoryIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Categorie Identité :");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnresetfilter.setBackground(new java.awt.Color(52, 104, 86));
        btnresetfilter.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnresetfilter.setForeground(new java.awt.Color(255, 255, 255));
        btnresetfilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/refresh.png"))); // NOI18N
        btnresetfilter.setText("réinitialiser le filtre");
        btnresetfilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetfilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboCateoryID, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnresetfilter))
                    .addComponent(combogenre, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combogenre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboCateoryID, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnresetfilter))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnrechercher.setBackground(new java.awt.Color(36, 104, 97));
        btnrechercher.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnrechercher.setForeground(new java.awt.Color(255, 255, 255));
        btnrechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/search.png"))); // NOI18N
        btnrechercher.setText("Rechercher");
        btnrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1077, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(btnrechercher)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnrechercher)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void showinformations(){
         try {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/producttbl", "root", "");
    String query = "SELECT category_ID, NumberID, name, gender, date_of_birth, address, email, phone_number FROM customer";
    Statement stmt = conn.createStatement();
    ResultSet rs = stmt.executeQuery(query);

    DefaultTableModel model = (DefaultTableModel) tableClient.getModel();
    model.setRowCount(0); 
    while (rs.next()) {
        String categoryid = rs.getString("category_ID");
        String numberId = rs.getString("NumberID");
        String name = rs.getString("name");
        String gender = rs.getString("gender");
        String dateOfBirth = rs.getString("date_of_birth");
        String address = rs.getString("address");
        String email = rs.getString("email");
        String phoneNumber = rs.getString("phone_number");

        model.addRow(new Object[]{categoryid, numberId, name, gender, dateOfBirth, address, email, phoneNumber});
    }

    stmt.close();
    conn.close();
} catch (SQLException e) {
    e.printStackTrace();
}
     }
    private void tableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientMouseClicked
         
    }//GEN-LAST:event_tableClientMouseClicked

    private void tableClientAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tableClientAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tableClientAncestorAdded

    private void btnrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechercherActionPerformed
       try {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/producttbl", "root", "");

    String selectedGender = combogenre.getSelectedItem().toString();
    String selectedIDCategory = comboCateoryID.getSelectedItem().toString();

    String query = "SELECT * FROM customer WHERE gender = ? AND Category_ID = ?";
    PreparedStatement ps = conn.prepareStatement(query);
    ps.setString(1, selectedGender.toLowerCase());
    ps.setString(2, selectedIDCategory.toLowerCase());

    ResultSet rs = ps.executeQuery();

    DefaultTableModel model = (DefaultTableModel) tableClient.getModel();
    model.setRowCount(0); // Clear the table
    while (rs.next()) {
        String categoryid = rs.getString("category_ID");
        String numberId = rs.getString("NumberID");
        String name = rs.getString("name");
        String gender = rs.getString("gender");
        String dateOfBirth = rs.getString("date_of_birth");
        String address = rs.getString("address");
        String email = rs.getString("email");
        String phoneNumber = rs.getString("phone_number");

        model.addRow(new Object[]{categoryid, numberId, name, gender, dateOfBirth, address, email, phoneNumber});
    }

    ps.close();
    conn.close();
} catch (SQLException ex) {
    ex.printStackTrace();
}




    }//GEN-LAST:event_btnrechercherActionPerformed

    private void comboCateoryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCateoryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCateoryIDActionPerformed

    private void btnresetfilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetfilterActionPerformed
       combogenre.setSelectedIndex(0); 
    comboCateoryID.setSelectedIndex(0); 
    
    showinformations(); 
    }//GEN-LAST:event_btnresetfilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformationsClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformationsClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformationsClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformationsClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformationsClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrechercher;
    private javax.swing.JButton btnresetfilter;
    private javax.swing.JComboBox<String> comboCateoryID;
    private javax.swing.JComboBox<String> combogenre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableClient;
    // End of variables declaration//GEN-END:variables
}
