/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hamamspa;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author rochdi
 */
public class RechercheChambre extends javax.swing.JFrame {

    /**
     * Creates new form RechercheChambre
     */
    public RechercheChambre() {
        initComponents();
        afficherchambre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChambre = new javax.swing.JTable();
        btnrechercher = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combotypeChambre = new javax.swing.JComboBox<>();
        checkboxAvailable = new javax.swing.JCheckBox();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 104, 97));
        jPanel1.setPreferredSize(new java.awt.Dimension(1599, 1088));

        tableChambre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129)));
        tableChambre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Room", "Disponsibilité", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableChambre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableChambre.setGridColor(new java.awt.Color(0, 0, 153));
        tableChambre.setRowHeight(40);
        tableChambre.setSelectionBackground(new java.awt.Color(11, 114, 129));
        tableChambre.setShowGrid(true);
        tableChambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableChambreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableChambreMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tableChambre);

        btnrechercher.setBackground(new java.awt.Color(52, 104, 86));
        btnrechercher.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnrechercher.setForeground(new java.awt.Color(255, 255, 255));
        btnrechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/search.png"))); // NOI18N
        btnrechercher.setText("Rechercher");
        btnrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechercherActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(11, 114, 129));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Filter :");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        combotypeChambre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salle Coiffure", "Salle Massage", "Salle Hamam" }));

        checkboxAvailable.setFont(new java.awt.Font("Sitka Heading", 3, 18)); // NOI18N
        checkboxAvailable.setForeground(new java.awt.Color(255, 255, 255));
        checkboxAvailable.setText("Afficher Disponible");
        checkboxAvailable.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), null));
        checkboxAvailable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkboxAvailable.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnreset.setBackground(new java.awt.Color(52, 104, 86));
        btnreset.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/refresh.png"))); // NOI18N
        btnreset.setText("réinitialiser le filtre");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(combotypeChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(checkboxAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnreset)
                .addGap(241, 241, 241))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(combotypeChambre, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkboxAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnreset)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addComponent(btnrechercher)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void afficherchambre(){
          try {
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/producttbl", "root", "");
    String query = "SELECT * FROM room";
    Statement stmt = conn.createStatement();
    ResultSet rs = stmt.executeQuery(query);


    DefaultTableModel model = (DefaultTableModel) tableChambre.getModel();
    model.setRowCount(0); 
    while (rs.next()) {
        int room = rs.getInt("room");
        String disponsibilite = rs.getString("ava");
        String category = rs.getString("status");
       
        model.addRow(new Object[]{room, disponsibilite, category});
    }

    stmt.close();
    conn.close();
} catch (SQLException e) {
    e.printStackTrace();
}

    }
    private void tableChambreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableChambreMouseClicked

       
    }//GEN-LAST:event_tableChambreMouseClicked

    private void tableChambreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableChambreMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableChambreMouseEntered

    private void btnrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechercherActionPerformed
       String Q = "select * from Room where status = '" + combotypeChambre.getSelectedItem() + "'";
String Q1 = "select * from Room where ava = 'Disponible' And status = '" + combotypeChambre.getSelectedItem() + "'";
try {
    conn c = new conn();
    java.sql.ResultSet resultSet;
    if (checkboxAvailable.isSelected()) {
        resultSet = c.statement.executeQuery(Q1);
    } else {
        resultSet = c.statement.executeQuery(Q);
    }
    
    // Create a DefaultTableModel
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Room");
    model.addColumn("ava");
    model.addColumn("status");
    
    while (resultSet.next()) {
        int room = resultSet.getInt("room");
        String disponsibilite = resultSet.getString("ava");
        String category = resultSet.getString("status");
        model.addRow(new Object[]{room, disponsibilite, category});
    }
    
    tableChambre.setModel(model);
    
    resultSet.close();
    c.statement.close();
    c.connection.close();
} catch (Exception E) {
    E.printStackTrace();
}



    }//GEN-LAST:event_btnrechercherActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        combotypeChambre.setSelectedIndex(0);
        afficherchambre();
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RechercheChambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RechercheChambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RechercheChambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RechercheChambre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RechercheChambre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrechercher;
    private javax.swing.JButton btnreset;
    private javax.swing.JCheckBox checkboxAvailable;
    private javax.swing.JComboBox<String> combotypeChambre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableChambre;
    // End of variables declaration//GEN-END:variables
}
