/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hamamspa;

import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import javax.swing.Timer;

/**
 *
 * @author rochdi
 */
public class SecrétaireMenu extends javax.swing.JFrame {

    /**
     * Creates new form SecrétaireMenu
     */
    public SecrétaireMenu() {
        initComponents();
        datetime();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        tabReceptionMenu.setTabPlacement(JTabbedPane.TOP);
        tabReceptionMenu.setTabLayoutPolicy(JTabbedPane.WRAP_TAB_LAYOUT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmenu = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelitems = new javax.swing.JPanel();
        lblajouterclient = new javax.swing.JLabel();
        panelselling = new javax.swing.JPanel();
        panelviewsells = new javax.swing.JPanel();
        lbldepartclient = new javax.swing.JLabel();
        lblmettreajourChambre = new javax.swing.JLabel();
        lblinformationClient = new javax.swing.JLabel();
        lblrechercheChambre = new javax.swing.JLabel();
        lblmettreajourChambre1 = new javax.swing.JLabel();
        lblreservation = new javax.swing.JLabel();
        lblsell = new javax.swing.JLabel();
        lblsell1 = new javax.swing.JLabel();
        lblDATETIME = new javax.swing.JLabel();
        tabReceptionMenu = new javax.swing.JTabbedPane();
        tabajouterclient = new javax.swing.JLabel();
        tabdepartclient = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setUndecorated(true);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                MAXIMIZED_BOTH(evt);
            }
        });

        panelmenu.setBackground(new java.awt.Color(36, 104, 97));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gestion Hamam & Spa");

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        panelitems.setBackground(new java.awt.Color(11, 114, 129));
        panelitems.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblajouterclient.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblajouterclient.setForeground(new java.awt.Color(255, 255, 255));
        lblajouterclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/client (1).png"))); // NOI18N
        lblajouterclient.setText("Ajouter Client");
        lblajouterclient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129)));
        lblajouterclient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblajouterclient.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblajouterclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblajouterclientMousePressed(evt);
            }
        });

        panelselling.setBackground(new java.awt.Color(11, 114, 129));
        panelselling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelsellingMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelsellingLayout = new javax.swing.GroupLayout(panelselling);
        panelselling.setLayout(panelsellingLayout);
        panelsellingLayout.setHorizontalGroup(
            panelsellingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelsellingLayout.setVerticalGroup(
            panelsellingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        panelviewsells.setBackground(new java.awt.Color(11, 114, 129));

        javax.swing.GroupLayout panelviewsellsLayout = new javax.swing.GroupLayout(panelviewsells);
        panelviewsells.setLayout(panelviewsellsLayout);
        panelviewsellsLayout.setHorizontalGroup(
            panelviewsellsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelviewsellsLayout.setVerticalGroup(
            panelviewsellsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        lbldepartclient.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbldepartclient.setForeground(new java.awt.Color(255, 255, 255));
        lbldepartclient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/check-out.png"))); // NOI18N
        lbldepartclient.setText("Libérer Client");
        lbldepartclient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbldepartclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbldepartclientMousePressed(evt);
            }
        });

        lblmettreajourChambre.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblmettreajourChambre.setForeground(new java.awt.Color(255, 255, 255));
        lblmettreajourChambre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/steam.png"))); // NOI18N
        lblmettreajourChambre.setText("Mettre A Jour Chambre");
        lblmettreajourChambre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblmettreajourChambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmettreajourChambreMousePressed(evt);
            }
        });

        lblinformationClient.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblinformationClient.setForeground(new java.awt.Color(255, 255, 255));
        lblinformationClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/target.png"))); // NOI18N
        lblinformationClient.setText("Information Client");
        lblinformationClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblinformationClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblinformationClientMousePressed(evt);
            }
        });

        lblrechercheChambre.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblrechercheChambre.setForeground(new java.awt.Color(255, 255, 255));
        lblrechercheChambre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/search.png"))); // NOI18N
        lblrechercheChambre.setText("Recherche Chambre");
        lblrechercheChambre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblrechercheChambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblrechercheChambreMousePressed(evt);
            }
        });

        lblmettreajourChambre1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblmettreajourChambre1.setForeground(new java.awt.Color(255, 255, 255));
        lblmettreajourChambre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/update.png"))); // NOI18N
        lblmettreajourChambre1.setText("Mettre A Jour Départ");
        lblmettreajourChambre1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblmettreajourChambre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblmettreajourChambre1MousePressed(evt);
            }
        });

        lblreservation.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblreservation.setForeground(new java.awt.Color(255, 255, 255));
        lblreservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/reserve.png"))); // NOI18N
        lblreservation.setText("Ajouter Reservation");
        lblreservation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblreservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblreservationMousePressed(evt);
            }
        });

        lblsell.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblsell.setForeground(new java.awt.Color(255, 255, 255));
        lblsell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/shopping-bag.png"))); // NOI18N
        lblsell.setText("Vendre Produit");
        lblsell.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129)));
        lblsell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblsell.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblsell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblsellMousePressed(evt);
            }
        });

        lblsell1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblsell1.setForeground(new java.awt.Color(255, 255, 255));
        lblsell1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/exit.png"))); // NOI18N
        lblsell1.setText("Quitter");
        lblsell1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129)));
        lblsell1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblsell1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lblsell1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblsell1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelitemsLayout = new javax.swing.GroupLayout(panelitems);
        panelitems.setLayout(panelitemsLayout);
        panelitemsLayout.setHorizontalGroup(
            panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelviewsells, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelitemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmettreajourChambre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelitemsLayout.createSequentialGroup()
                        .addGroup(panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelitemsLayout.createSequentialGroup()
                                .addGroup(panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblsell, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelitemsLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(lblsell1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelselling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelitemsLayout.createSequentialGroup()
                                .addGroup(panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblajouterclient, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblreservation)
                                    .addComponent(lbldepartclient, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblmettreajourChambre1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 25, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panelitemsLayout.createSequentialGroup()
                        .addGroup(panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblrechercheChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblinformationClient, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelitemsLayout.setVerticalGroup(
            panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelitemsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblajouterclient, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblreservation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbldepartclient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblmettreajourChambre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblmettreajourChambre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrechercheChambre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblinformationClient)
                .addGroup(panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelitemsLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(panelselling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelitemsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsell, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblsell1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(panelviewsells, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblDATETIME.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        lblDATETIME.setForeground(new java.awt.Color(255, 255, 255));
        lblDATETIME.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDATETIME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/clock.png"))); // NOI18N

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelitems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDATETIME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDATETIME, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelitems, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabReceptionMenu.setBackground(new java.awt.Color(36, 104, 97));
        tabReceptionMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129), new java.awt.Color(11, 114, 129)));
        tabReceptionMenu.setForeground(new java.awt.Color(255, 255, 255));
        tabReceptionMenu.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabReceptionMenu.setAutoscrolls(true);
        tabReceptionMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabReceptionMenu.setName("Menu Hamam Spa"); // NOI18N
        tabReceptionMenu.setOpaque(true);
        tabReceptionMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabReceptionMenuMousePressed(evt);
            }
        });

        tabajouterclient.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        tabReceptionMenu.addTab("Ajouter Client", tabajouterclient);

        tabdepartclient.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        tabdepartclient.setText("jLabel2");
        tabdepartclient.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabReceptionMenu.addTab("Ajouter Reservation", tabdepartclient);

        jLabel4.setText("jLabel4");
        tabReceptionMenu.addTab("Depart Client", jLabel4);

        jLabel5.setText("jLabel5");
        tabReceptionMenu.addTab("Mettre A Jour depart", jLabel5);

        jLabel6.setText("jLabel6");
        tabReceptionMenu.addTab("Mettre A Jour Chambre", jLabel6);

        jLabel1.setText("jLabel1");
        tabReceptionMenu.addTab("Information Client", jLabel1);

        jLabel2.setText("jLabel2");
        tabReceptionMenu.addTab("Vendre Produit", jLabel2);

        jLabel7.setText("jLabel7");
        tabReceptionMenu.addTab("Recherche Chambre", jLabel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabReceptionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabReceptionMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
            .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabReceptionMenu.getAccessibleContext().setAccessibleDescription("Menu Hamam Spa");

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void datetime(){
        Timer timer = new Timer(1000, e -> {
       Date date = new Date();
       lblDATETIME.setText("" + date);
      });
      timer.start();
    }
    
    private void lblajouterclientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblajouterclientMousePressed
         AjouterClient client = new AjouterClient();
    
    tabReceptionMenu.setComponentAt(0, client.getContentPane());
    
    tabReceptionMenu.setTitleAt(0, "Ajouter Client");

    tabReceptionMenu.setSelectedIndex(0);
    }//GEN-LAST:event_lblajouterclientMousePressed

    private void lbldepartclientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldepartclientMousePressed
      Départ  depart = new Départ();
    
    tabReceptionMenu.setComponentAt(2, depart.getContentPane());
    
    tabReceptionMenu.setTitleAt(2, "Départ Client");

    tabReceptionMenu.setSelectedIndex(2);
    }//GEN-LAST:event_lbldepartclientMousePressed

    private void panelsellingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsellingMousePressed
        
    }//GEN-LAST:event_panelsellingMousePressed

    private void lblmettreajourChambreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmettreajourChambreMousePressed
        MettreAjourChambre mettreajourchamber = new MettreAjourChambre();
    
    tabReceptionMenu.setComponentAt(4, mettreajourchamber.getContentPane());
    
    tabReceptionMenu.setTitleAt(4, "Mettre A Jour Chambre");

    tabReceptionMenu.setSelectedIndex(4);
    }//GEN-LAST:event_lblmettreajourChambreMousePressed

    private void lblinformationClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinformationClientMousePressed
        InformationsClient informationClient = new InformationsClient();
    
    tabReceptionMenu.setComponentAt(6, informationClient.getContentPane());
    
    tabReceptionMenu.setTitleAt(6, "Informations Client");

    tabReceptionMenu.setSelectedIndex(6);
    }//GEN-LAST:event_lblinformationClientMousePressed

    private void lblrechercheChambreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrechercheChambreMousePressed
        RechercheChambre recherchechambre = new RechercheChambre();
    
    tabReceptionMenu.setComponentAt(5, recherchechambre.getContentPane());
    
    tabReceptionMenu.setTitleAt(5, "Recherche Chambre");

    tabReceptionMenu.setSelectedIndex(5);
    }//GEN-LAST:event_lblrechercheChambreMousePressed

    private void lblvendreProduitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblvendreProduitMousePressed
       VendreProduit vendreproduit = new VendreProduit();
    
    tabReceptionMenu.setComponentAt(7, vendreproduit.getContentPane());
    
    tabReceptionMenu.setTitleAt(7, "Vendre Produit");

    tabReceptionMenu.setSelectedIndex(7);
    }//GEN-LAST:event_lblvendreProduitMousePressed

    private void lblmettreajourChambre1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmettreajourChambre1MousePressed
       DépartInformations mettreajourdepart = new DépartInformations();
    
    tabReceptionMenu.setComponentAt(3, mettreajourdepart.getContentPane());
    
    tabReceptionMenu.setTitleAt(3, "Mettra A Jour Départ");

    tabReceptionMenu.setSelectedIndex(3);
    }//GEN-LAST:event_lblmettreajourChambre1MousePressed

    private void lblreservationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblreservationMousePressed
      SelectionnerReservation res = new SelectionnerReservation();
      
    tabReceptionMenu.setComponentAt(1, res.getContentPane());
    
    tabReceptionMenu.setTitleAt(1, "Ajouter Reservation");

    tabReceptionMenu.setSelectedIndex(1);
    }//GEN-LAST:event_lblreservationMousePressed

    private void tabReceptionMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabReceptionMenuMousePressed
        SelectionnerReservation.getFrames();
        SelectionnerReservation.getWindows();
    }//GEN-LAST:event_tabReceptionMenuMousePressed

    private void MAXIMIZED_BOTH(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_MAXIMIZED_BOTH
        // TODO add your handling code here:
    }//GEN-LAST:event_MAXIMIZED_BOTH

    private void lblsellMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsellMousePressed
        VendreProduit vendreproduit = new VendreProduit();
    
    tabReceptionMenu.setComponentAt(7, vendreproduit.getContentPane());
    
    tabReceptionMenu.setTitleAt(7, "Vendre Produit");

    tabReceptionMenu.setSelectedIndex(7);
    }//GEN-LAST:event_lblsellMousePressed

    private void lblsell1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsell1MousePressed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblsell1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecrétaireMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecrétaireMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecrétaireMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecrétaireMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecrétaireMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDATETIME;
    private javax.swing.JLabel lblajouterclient;
    private javax.swing.JLabel lbldepartclient;
    private javax.swing.JLabel lblinformationClient;
    private javax.swing.JLabel lblmettreajourChambre;
    private javax.swing.JLabel lblmettreajourChambre1;
    private javax.swing.JLabel lblrechercheChambre;
    private javax.swing.JLabel lblreservation;
    private javax.swing.JLabel lblsell;
    private javax.swing.JLabel lblsell1;
    private javax.swing.JPanel panelitems;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JPanel panelselling;
    private javax.swing.JPanel panelviewsells;
    private javax.swing.JTabbedPane tabReceptionMenu;
    private javax.swing.JLabel tabajouterclient;
    private javax.swing.JLabel tabdepartclient;
    // End of variables declaration//GEN-END:variables
}
