/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrateur;

import java.awt.Dimension;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

import javax.swing.Timer;

/**
 *
 * @author rochdi
 */
public class Admin extends javax.swing.JFrame {

    /**s
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        datetime();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
               
                

    }
    private void hideTabLabels() {
        for (int i = 0; i < tabchambre.getTabCount(); i++) {
            JPanel emptyPanel = new JPanel();
            emptyPanel.setPreferredSize(new Dimension(0, 0));
            tabchambre.setTabComponentAt(i, emptyPanel);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmenu = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelitems = new javax.swing.JPanel();
        lblajouteremployee = new javax.swing.JLabel();
        panelselling = new javax.swing.JPanel();
        panelviewsells = new javax.swing.JPanel();
        lblProduit = new javax.swing.JLabel();
        lblchambre = new javax.swing.JLabel();
        lblservices = new javax.swing.JLabel();
        lbllistemployee = new javax.swing.JLabel();
        lblventes = new javax.swing.JLabel();
        lblquitter = new javax.swing.JLabel();
        lblReservations = new javax.swing.JLabel();
        lblDATETIME = new javax.swing.JLabel();
        tabchambre = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 104, 97));
        setUndecorated(true);

        panelmenu.setBackground(new java.awt.Color(36, 104, 97));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hamam & Spa");

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        panelitems.setBackground(new java.awt.Color(11, 114, 129));
        panelitems.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panelitems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblajouteremployee.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblajouteremployee.setForeground(new java.awt.Color(255, 255, 255));
        lblajouteremployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/contract.png"))); // NOI18N
        lblajouteremployee.setText("Ajouter Employee");
        lblajouteremployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblajouteremployeeMousePressed(evt);
            }
        });

        panelselling.setBackground(new java.awt.Color(11, 114, 129));
        panelselling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelsellingMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelsellingLayout = new javax.swing.GroupLayout(panelselling);
        panelselling.setLayout(panelsellingLayout);
        panelsellingLayout.setHorizontalGroup(
            panelsellingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelsellingLayout.setVerticalGroup(
            panelsellingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        panelviewsells.setBackground(new java.awt.Color(11, 114, 129));

        javax.swing.GroupLayout panelviewsellsLayout = new javax.swing.GroupLayout(panelviewsells);
        panelviewsells.setLayout(panelviewsellsLayout);
        panelviewsellsLayout.setHorizontalGroup(
            panelviewsellsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelviewsellsLayout.setVerticalGroup(
            panelviewsellsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        lblProduit.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblProduit.setForeground(new java.awt.Color(255, 255, 255));
        lblProduit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/add-to-basket.png"))); // NOI18N
        lblProduit.setText("Ajouter Produit");
        lblProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblProduitMousePressed(evt);
            }
        });

        lblchambre.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblchambre.setForeground(new java.awt.Color(255, 255, 255));
        lblchambre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/steam.png"))); // NOI18N
        lblchambre.setText("Ajouter Chambre");
        lblchambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblchambreMousePressed(evt);
            }
        });

        lblservices.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblservices.setForeground(new java.awt.Color(255, 255, 255));
        lblservices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/add services.png"))); // NOI18N
        lblservices.setText("Ajouter Services");
        lblservices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblservicesMousePressed(evt);
            }
        });

        lbllistemployee.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbllistemployee.setForeground(new java.awt.Color(255, 255, 255));
        lbllistemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/division.png"))); // NOI18N
        lbllistemployee.setText("List Employee");
        lbllistemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbllistemployeeMousePressed(evt);
            }
        });

        lblventes.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblventes.setForeground(new java.awt.Color(255, 255, 255));
        lblventes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/viewsells.png"))); // NOI18N
        lblventes.setText("Tous Les ventes");
        lblventes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblventesMousePressed(evt);
            }
        });

        lblquitter.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblquitter.setForeground(new java.awt.Color(255, 255, 255));
        lblquitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/exit.png"))); // NOI18N
        lblquitter.setText("Quitter");
        lblquitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblquitterMousePressed(evt);
            }
        });

        lblReservations.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblReservations.setForeground(new java.awt.Color(255, 255, 255));
        lblReservations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/waiting-list.png"))); // NOI18N
        lblReservations.setText("Tous Les Reservations");
        lblReservations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblReservationsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelitemsLayout = new javax.swing.GroupLayout(panelitems);
        panelitems.setLayout(panelitemsLayout);
        panelitemsLayout.setHorizontalGroup(
            panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelviewsells, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelitemsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelitemsLayout.createSequentialGroup()
                        .addGroup(panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelitemsLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblquitter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblventes, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelselling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addComponent(lblservices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblajouteremployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelitemsLayout.createSequentialGroup()
                        .addGroup(panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllistemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblchambre)
                            .addComponent(lblProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelitemsLayout.setVerticalGroup(
            panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelitemsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblajouteremployee)
                .addGap(18, 18, 18)
                .addComponent(lblProduit)
                .addGap(18, 18, 18)
                .addComponent(lblchambre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblservices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbllistemployee)
                .addGroup(panelitemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelitemsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelselling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(panelitemsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblventes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblquitter, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(panelviewsells, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblDATETIME.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        lblDATETIME.setForeground(new java.awt.Color(255, 255, 255));
        lblDATETIME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgHamam/clock.png"))); // NOI18N

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelitems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelmenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblDATETIME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDATETIME, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelitems, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabchambre.setBackground(new java.awt.Color(36, 104, 97));
        tabchambre.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(36, 104, 97));
        jLabel1.setText("Hamam Spa");
        tabchambre.addTab("Ajouter Employee", jLabel1);

        jLabel2.setText("jLabel2");
        tabchambre.addTab("Ajouter Produit", jLabel2);
        tabchambre.addTab("Ajouter Chambre", jTabbedPane1);

        jLabel3.setText("jLabel3");
        tabchambre.addTab("Ajouter Services", jLabel3);

        jLabel4.setText("jLabel4");
        tabchambre.addTab("List Employee", jLabel4);

        jLabel5.setText("jLabel5");
        tabchambre.addTab("Tous Les Ventes", jLabel5);

        jLabel6.setText("jLabel6");
        tabchambre.addTab("Tous Les Reservations", jLabel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabchambre, javax.swing.GroupLayout.PREFERRED_SIZE, 1449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabchambre, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private void datetime(){
        Timer timer = new Timer(1000, e -> {
       Date date = new Date();
       lblDATETIME.setText("" + date);
      });
      timer.start();
    }
 
        
    


        
    private void lblajouteremployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblajouteremployeeMousePressed
    AjouterEmploye ajouterEmploye = new AjouterEmploye();
    
    tabchambre.setComponentAt(0, ajouterEmploye.getContentPane());
    
    tabchambre.setTitleAt(0, "Ajouter Employee");

    tabchambre.setSelectedIndex(0);
        
    }//GEN-LAST:event_lblajouteremployeeMousePressed

    private void lblProduitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProduitMousePressed
        AjouterProduit produit = new AjouterProduit();
    
    tabchambre.setComponentAt(1, produit.getContentPane());
    
    tabchambre.setTitleAt(1, "Ajouter Produit");

    tabchambre.setSelectedIndex(1);
    }//GEN-LAST:event_lblProduitMousePressed

    private void panelsellingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsellingMousePressed

    }//GEN-LAST:event_panelsellingMousePressed

    private void lblchambreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblchambreMousePressed
        AjouterChambre ajouterchambre = new AjouterChambre();
    
   
    tabchambre.setComponentAt(2, ajouterchambre.getContentPane());
    
   
    tabchambre.setTitleAt(2, "Ajouter Chambre");

   
    tabchambre.setSelectedIndex(2);
    }//GEN-LAST:event_lblchambreMousePressed

    private void lblquitterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblquitterMousePressed
        new hamamspa.Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblquitterMousePressed

    private void lbllistemployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllistemployeeMousePressed
        ListEmployer listemployee = new ListEmployer();
    
   
    tabchambre.setComponentAt(4, listemployee.getContentPane());
    
   
    tabchambre.setTitleAt(4, "List Employee");

   
    tabchambre.setSelectedIndex(4);
    }//GEN-LAST:event_lbllistemployeeMousePressed

    private void lblservicesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblservicesMousePressed
        AjouterService ajouterservice = new AjouterService();
    
   
    tabchambre.setComponentAt(3, ajouterservice.getContentPane());
    
   
    tabchambre.setTitleAt(3, "Ajouter Services");

   
    tabchambre.setSelectedIndex(3);
    }//GEN-LAST:event_lblservicesMousePressed

    private void lblventesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblventesMousePressed
         viewsells mesventes = new viewsells();
    
   
    tabchambre.setComponentAt(5, mesventes.getContentPane());
    
   
    tabchambre.setTitleAt(5, "Tous Les Ventes");

   
    tabchambre.setSelectedIndex(5);
    }//GEN-LAST:event_lblventesMousePressed

    private void lblReservationsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReservationsMousePressed
        TousLesReservation Touslesreservation = new TousLesReservation();
    
   
    tabchambre.setComponentAt(6, Touslesreservation.getContentPane());
    
   
    tabchambre.setTitleAt(6, "Tous Les reservations");

   
    tabchambre.setSelectedIndex(6);
    }//GEN-LAST:event_lblReservationsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDATETIME;
    private javax.swing.JLabel lblProduit;
    private javax.swing.JLabel lblReservations;
    private javax.swing.JLabel lblajouteremployee;
    private javax.swing.JLabel lblchambre;
    private javax.swing.JLabel lbllistemployee;
    private javax.swing.JLabel lblquitter;
    private javax.swing.JLabel lblservices;
    private javax.swing.JLabel lblventes;
    private javax.swing.JPanel panelitems;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JPanel panelselling;
    private javax.swing.JPanel panelviewsells;
    private javax.swing.JTabbedPane tabchambre;
    // End of variables declaration//GEN-END:variables
}
